permalink: /:categories/:year/:month/:day/:title

exclude: [".rbenv-version", "README.md", "Rakefile"]
auto: true
pygments: true

title : Terracoding
tagline:
author :
  name : Dominic Wroblewski
  email : domness@me.com
  github : domness
  twitter : domness

production_url : http://terracoding.github.com

JB :
  version : 0.1.0
  BASE_PATH : ""
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  comments :
    provider : disqus
    disqus :
      short_name : domness
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      apikey : 123
  analytics :
    provider : google
    google :
        tracking_id : 'UA-28758767-1'
    getclicky :
      site_id :
  sharing :
    provider : [tweet, plusone, like, reddit]

name: "Terracoding"
description: "Terracoding Blog"
url: "http://terracoding.github.com"
